import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, JetBrains_Mono, Michroma, Orbitron } from "next/font/google";
import { MotionConfig } from "framer-motion";
import Script from "next/script";
import { SITE_URL } from "@/lib/seo/site";
import { safeJsonLd } from "@/lib/seo/json-ld";
import { getSiteSettings } from "@/lib/settings/repository";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// JetBrains Mono, not Geist Mono — Geist's the literal default face in
// most AI website builders/templates, so the whole site (body text is
// monospace everywhere, see globals.css) was reading as generic/AI-
// generated by association. JetBrains Mono keeps the same terminal/
// technical register but has more of its own character in the letterforms.
const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono-face",
  subsets: ["latin"],
});

// Only used for the homepage hero's "DIAMANTES DESIGNS" headline — a
// distinct display face for that one title, not a site-wide font change.
// Google only ships Michroma at a single weight (400).
const michroma = Michroma({
  variable: "--font-michroma",
  subsets: ["latin"],
  weight: "400",
});

// Bold geometric sci-fi face — the closest real match to the "METAMORFOSIS"
// reference's angular/cut letterforms; that exact wordmark looks like a
// custom-drawn logotype rather than a stock font, so this is a stylistic
// match, not pixel-identical.
const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: "700",
});

export async function generateMetadata(): Promise<Metadata> {
  const settings = await getSiteSettings();
  const { seoDefaultTitle: title, seoDefaultDescription: description } = settings;

  return {
    metadataBase: new URL(SITE_URL),
    title: {
      default: title,
      template: "%s | Diamantes 3Designs",
    },
    description,
    keywords: settings.seoKeywords,
    authors: [{ name: "Diamantes 3Designs" }],
    alternates: {
      canonical: SITE_URL,
    },
    openGraph: {
      title,
      description,
      url: SITE_URL,
      siteName: "Diamantes 3Designs",
      type: "website",
      locale: "en_US",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
    robots: {
      index: true,
      follow: true,
    },
    // Proves ownership of the domain to Google Search Console — lets us
    // request re-indexing on demand (e.g. after a favicon fix) instead of
    // waiting for Google's own crawl schedule.
    verification: {
      google: "fvmclRr8xwbXgZ4uut9BWA6ga9M3R36kQUUpq18dzeI",
    },
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getSiteSettings();
  // Read directly from the cookie ThemeToggle now also writes (not just
  // localStorage, which the server can't see) — the initial HTML already
  // carries the right data-theme for a returning visitor, instead of
  // always assuming "light" and correcting client-side a moment later,
  // which is what caused a visible flash between themes on load.
  const cookieStore = await cookies();
  const savedTheme = cookieStore.get("d3d-theme")?.value;
  const initialTheme = savedTheme === "dark" ? "dark" : "light";

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "ProfessionalService",
    name: "Diamantes 3Designs",
    url: SITE_URL,
    description: settings.seoDefaultDescription,
    address: {
      "@type": "PostalAddress",
      ...(settings.addressStreet ? { streetAddress: settings.addressStreet } : {}),
      ...(settings.addressCity ? { addressLocality: settings.addressCity } : {}),
      ...(settings.addressPostalCode ? { postalCode: settings.addressPostalCode } : {}),
      addressCountry: settings.addressCountry,
    },
    areaServed: settings.areaServed,
    knowsAbout: settings.seoKnowsAbout,
    sameAs: [settings.instagramUrl, settings.tiktokUrl],
  };

  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      data-theme={initialTheme}
      // suppressHydrationWarning still needed: the theme-sync script below
      // can still correct this attribute client-side (the one case the
      // cookie above doesn't cover — see its own comment), which React
      // would otherwise flag as a hydration mismatch on this specific
      // attribute even though it's expected/handled.
      suppressHydrationWarning
      className={`${geistSans.variable} ${jetbrainsMono.variable} ${michroma.variable} ${orbitron.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* beforeInteractive scripts are injected into <head> by Next itself
            regardless of where they're declared inside <body> — confirmed
            against next/script's own bundled docs, which place the example
            here, not between <html> and <body>. Placing it outside <body>
            (as this previously did) is invalid HTML — <script> can't be a
            direct child of <html> — and reproduced a hydration-mismatch
            error on every single page.

            The <html data-theme> attribute above (read from the cookie
            ThemeToggle writes) already carries the right value for a
            returning visitor in the very first byte of HTML — this script
            is now just a defensive correction for the one case that
            cookie can't cover: a visitor whose browser blocks/clears
            cookies but still has the older localStorage value (from
            before this cookie was added, or from a browser configured
            that way generally). It only touches the DOM when the two
            genuinely disagree, so it's a no-op read-and-compare on every
            normal load, not an unconditional overwrite racing the SSR'd
            value — that unconditional overwrite is exactly what caused a
            visible flash between themes on load for anyone with a saved
            "dark" preference, since it always ran a moment *after* the
            server-rendered "light" default had already painted. */}
        <Script id="theme-sync" strategy="beforeInteractive">
          {`(function(){try{var s=localStorage.getItem('d3d-theme');if(s&&s!==document.documentElement.getAttribute('data-theme')){document.documentElement.setAttribute('data-theme',s);}}catch(e){}})();`}
        </Script>
        <MotionConfig reducedMotion="user">{children}</MotionConfig>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: safeJsonLd(jsonLd) }}
        />
      </body>
    </html>
  );
}
