import type { Metadata } from "next";
import { Geist, JetBrains_Mono, Michroma, Orbitron } from "next/font/google";
import { MotionConfig } from "framer-motion";
import Script from "next/script";
import { SITE_URL } from "@/lib/seo/site";
import { safeJsonLd } from "@/lib/seo/json-ld";
import { getSiteSettings } from "@/lib/settings/repository";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// JetBrains Mono, not Geist Mono — Geist's the literal default face in
// most AI website builders/templates, so the whole site (body text is
// monospace everywhere, see globals.css) was reading as generic/AI-
// generated by association. JetBrains Mono keeps the same terminal/
// technical register but has more of its own character in the letterforms.
const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono-face",
  subsets: ["latin"],
});

// Only used for the homepage hero's "DIAMANTES DESIGNS" headline — a
// distinct display face for that one title, not a site-wide font change.
// Google only ships Michroma at a single weight (400).
const michroma = Michroma({
  variable: "--font-michroma",
  subsets: ["latin"],
  weight: "400",
});

// Bold geometric sci-fi face — the closest real match to the "METAMORFOSIS"
// reference's angular/cut letterforms; that exact wordmark looks like a
// custom-drawn logotype rather than a stock font, so this is a stylistic
// match, not pixel-identical.
const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: "700",
});

export async function generateMetadata(): Promise<Metadata> {
  const settings = await getSiteSettings();
  const { seoDefaultTitle: title, seoDefaultDescription: description } = settings;

  return {
    metadataBase: new URL(SITE_URL),
    title: {
      default: title,
      template: "%s | Diamantes 3Designs",
    },
    description,
    keywords: settings.seoKeywords,
    authors: [{ name: "Diamantes 3Designs" }],
    alternates: {
      canonical: SITE_URL,
    },
    openGraph: {
      title,
      description,
      url: SITE_URL,
      siteName: "Diamantes 3Designs",
      type: "website",
      locale: "en_US",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
    robots: {
      index: true,
      follow: true,
    },
    // Proves ownership of the domain to Google Search Console — lets us
    // request re-indexing on demand (e.g. after a favicon fix) instead of
    // waiting for Google's own crawl schedule.
    verification: {
      google: "fvmclRr8xwbXgZ4uut9BWA6ga9M3R36kQUUpq18dzeI",
    },
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getSiteSettings();

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "ProfessionalService",
    name: "Diamantes 3Designs",
    url: SITE_URL,
    description: settings.seoDefaultDescription,
    address: {
      "@type": "PostalAddress",
      ...(settings.addressStreet ? { streetAddress: settings.addressStreet } : {}),
      ...(settings.addressCity ? { addressLocality: settings.addressCity } : {}),
      ...(settings.addressPostalCode ? { postalCode: settings.addressPostalCode } : {}),
      addressCountry: settings.addressCountry,
    },
    areaServed: settings.areaServed,
    knowsAbout: settings.seoKnowsAbout,
    sameAs: [settings.instagramUrl, settings.tiktokUrl],
  };

  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      // data-theme is set by the theme-init script below, before hydration —
      // React never renders this attribute itself, so it always "mismatches"
      // what SSR produced. This is the standard, documented way to tell
      // React that's expected for a specific, known attribute rather than a
      // real bug (see the effect it has on the console-noise: without this,
      // the invalid-nesting fix below still leaves a separate, cosmetic
      // hydration warning for this attribute alone).
      suppressHydrationWarning
      className={`${geistSans.variable} ${jetbrainsMono.variable} ${michroma.variable} ${orbitron.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* beforeInteractive scripts are injected into <head> by Next itself
            regardless of where they're declared inside <body> — confirmed
            against next/script's own bundled docs, which place the example
            here, not between <html> and <body>. Placing it outside <body>
            (as this previously did) is invalid HTML — <script> can't be a
            direct child of <html> — and reproduced a hydration-mismatch
            error on every single page. Sets data-theme on <html> before
            first paint, so there's no flash of the wrong theme. "d3d-theme"
            here must match THEME_STORAGE_KEY in components/ThemeToggle.tsx.
            The theme only ever affects markup inside [data-site-root] (the
            public site layout) — see app/globals.css — so this runs
            harmlessly on admin pages too. Defaults to light regardless of OS
            preference — a stored choice (from ThemeToggle) always wins, but
            a first-time visitor always starts on light rather than whatever
            their OS happens to prefer. */}
        <Script id="theme-init" strategy="beforeInteractive">
          {`(function(){try{var s=localStorage.getItem('d3d-theme');document.documentElement.setAttribute('data-theme',s||'light');}catch(e){}})();`}
        </Script>
        <MotionConfig reducedMotion="user">{children}</MotionConfig>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: safeJsonLd(jsonLd) }}
        />
      </body>
    </html>
  );
}
